export type AppRoutes =
    '/'
    | '/software'
    | '/software/architecture'
    | '/software/frontend'
    | '/software/backend'
    | '/sound'
    | '/sound/studio'
    | '/sound/soundtracks'
    | '/contact'
